# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kwidgetaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kidletime': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kactivities': '@stable'
    'network/ktp-common-internals': '@same'
